GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODc1NzQ0MjQsImV4cCI6MTY4NzY2MDgyNCwiYXVkIjoiNjQ5NjU3NWNjMWFmZjQyODljZTY3ZmI3IiwiaXNzIjoiQklTV0FfUlgifQ.9mfH1rHgzW0-l1gGtOAa5ldFmDsMqnA2f2T4UsQjwQQ

###
POST http://localhost:3000/auth/resister
Content-Type: application/json

{
    "name": "Mukesh Samantray",
    "email": "mukesh@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "mukesh@gmail.com",
    "password": "12345"
}


###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTXVrZXNoIFNhbWFudHJheSIsImlhdCI6MTY4ODI3OTczNywiZXhwIjoxNzE5ODM3MzM3LCJhdWQiOiI2NGExMWFiOWRjZTdhNDIyNDk0NzI5NTQiLCJpc3MiOiJCSVNXQV9SWCJ9.nirp04vASrSNPOaU7oP0i5q_CX0npwczJPGbXbHK-r4"
}
###
DELETE http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmlzd2FyYW5qYW4gQmVoZXJhIiwiaWF0IjoxNjg4MjkyMDE0LCJleHAiOjE3MTk4NDk2MTQsImF1ZCI6IjY0YTAzYmM5OGZkZGJlOWJjNzZjYjk0ZSIsImlzcyI6IkJJU1dBX1JYIn0.p6yAdVN0VqAl8QPwvb1lvPAYkGTI5b3-2MCw5M3CqAc

### Random url
GET http://localhost:3000/xyz



###NOTE ROUTES

### Getting all Notes
GET http://localhost:3000/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODg4MDU0MTksImV4cCI6MTY4ODg5MTgxOSwiYXVkIjoiNjRhMTFhYjlkY2U3YTQyMjQ5NDcyOTU0IiwiaXNzIjoiQklTV0FfUlgifQ.XojVQitdBDcZQrNnGQN_CRffO-3lC9c4q-izZThCNdo

### Getting a singel note by its id
GET http://localhost:3000/notes/64965807c1aff4289ce67fbc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODgwNDc1NDMsImV4cCI6MTY4ODEzMzk0MywiYXVkIjoiNjQ5NjU3NWNjMWFmZjQyODljZTY3ZmI3IiwiaXNzIjoiQklTV0FfUlgifQ.zJZv_fUbLejCc03brG6KpFoMJLT9dQqXGMCRDeSi_KM

### Creating a new note
POST http://localhost:3000/notes
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODg4MDU0MTksImV4cCI6MTY4ODg5MTgxOSwiYXVkIjoiNjRhMTFhYjlkY2U3YTQyMjQ5NDcyOTU0IiwiaXNzIjoiQklTV0FfUlgifQ.XojVQitdBDcZQrNnGQN_CRffO-3lC9c4q-izZThCNdo",
    "name": "good",
    "text": "evening",
    "color": "green"
}

###Update a note
PATCH http://localhost:3000/notes/64a7b82f6732e3e9ea883b35
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODg4MDU0MTksImV4cCI6MTY4ODg5MTgxOSwiYXVkIjoiNjRhMTFhYjlkY2U3YTQyMjQ5NDcyOTU0IiwiaXNzIjoiQklTV0FfUlgifQ.XojVQitdBDcZQrNnGQN_CRffO-3lC9c4q-izZThCNdo",
    "text": "hello earth",
    "color": "red"
}

###Delete a note
DELETE http://localhost:3000/notes/649d9088449982d9b046e4eb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODgwNDc1NDMsImV4cCI6MTY4ODEzMzk0MywiYXVkIjoiNjQ5NjU3NWNjMWFmZjQyODljZTY3ZmI3IiwiaXNzIjoiQklTV0FfUlgifQ.zJZv_fUbLejCc03brG6KpFoMJLT9dQqXGMCRDeSi_KM